# Generated by Django 5.2.3 on 2025-07-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorys',
        ),
    ]
