# Generated by Django 5.2.3 on 2025-07-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_category_categorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorys',
            new_name='Category',
        ),
    ]
