# Generated by Django 5.2.3 on 2025-07-31 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_categorys_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
