# Generated by Django 5.2.3 on 2025-08-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_user_alter_cart_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
