# Generated by Django 5.2.3 on 2025-08-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_updated_at_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
