# Generated by Django 5.2.3 on 2025-09-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cartitem_cart_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
    ]
