# Generated by Django 5.2.3 on 2025-09-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_order_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
